import { AiOutlineMobile } from 'react-icons/ai'
import { BsHouseDoor } from 'react-icons/bs'
import { FiMonitor } from 'react-icons/fi'
import { FaDog } from 'react-icons/fa'
import { BiCar, BiBed } from 'react-icons/bi'
import { RiMotorbikeLine, RiTShirt2Line } from 'react-icons/ri'
import { IoMdBusiness } from 'react-icons/io'
import { GiTennisRacket } from 'react-icons/gi'
import { GrServices } from 'react-icons/gr'
import { MdBusinessCenter, MdChildFriendly } from 'react-icons/md'
// https://www.olx.com.pk/payments/packages/consume/free/success
const noUser = {
    userPrimary: "https://firebasestorage.googleapis.com/v0/b/sellit-928cd.appspot.com/o/images%2Fuser.jpg?alt=media&token=74e7ace2-9099-4b13-9167-edc90d4bc9e4",
    userSecondary: "https://firebasestorage.googleapis.com/v0/b/sellit-928cd.appspot.com/o/images%2Fuser%20-%20secondary.png?alt=media&token=c1ce91af-9ae3-4b48-a1ce-a49c9586d4eb"
}
const noAd = {
    adImage: 'https://statics.olx.com.pk/olxpk/misc/emptyState_v1.png'
}
const categories = {
    "Mobiles": AiOutlineMobile,
    "Vehicles": BiCar,
    "Property": BsHouseDoor,
    "Electronics & Home Appliances": FiMonitor,
    "Bikes": RiMotorbikeLine,
    "Business, Industrial & Agriculture": IoMdBusiness,
    "Services": GrServices,
    "Jobs": MdBusinessCenter,
    "Animals": FaDog,
    "Furniture & Home Decor": BiBed,
    "Fashion & Beauty": RiTShirt2Line,
    "Books, Sports & Hobbies": GiTennisRacket,
    "Kids": MdChildFriendly
}
const cities = [
    "Karachi",
    "Lahore",
    "Faisalābād",
    "Serai",
    "Rāwalpindi",
    'Multān',
    "Gujrānwāla",
    "Hyderābād",
    "Peshāwar",
    "Abbottābād",
    "Islamabad",
    "Quetta",
    "Bannu",
    "Bahāwalpur",
    "Sargodha",
    "Siālkot",
    "Sukkur",
    "Lārkāna",
    "Sheikhupura",
    "Mīrpur Khās",
    "Rahīmyār Khān",
    "Kohāt",
    "Jhang Sadr",
    "Gujrāt",
    "Bardār",
    "Kasūr",
    "Dera Ghāzi Khān",
    "Masīwāla",
    "Nawābshāh",
    "Okāra",
    "Gilgit",
    "Chiniot",
    "Sādiqābād",
    "Turbat",
    "Dera Ismāīl Khān",
    "Chaman",
    "Zhob",
    "Mehra",
    "Parachinār",
    "Gwādar",
    "Kundiān",
    "Shahdād Kot",
    "Harīpur",
    "Matiāri",
    "Dera Allāhyār",
    "Lodhrān",
    "Batgrām",
    "Thatta",
    "Bāgh",
    "Badīn",
    "Mānsehra",
    "Ziārat",
    "Muzaffargarh",
    "Tando Allāhyār",
    "Dera Murād Jamāli",
    "Karak",
    "Mardan",
    "Uthal",
    "Nankāna Sāhib",
    "Bārkhān",
    "Hāfizābād",
    "Kotli",
    "Loralai",
    "Dera Bugti",
    "Jhang",
    "Sāhīwāl",
    "Sānghar",
    "Pākpattan",
    'Chakwāl',
    "Khushāb",
    'Ghotki',
    "Kohlu",
    "Khuzdār",
    "Awārān",
    "Nowshera",
    "Chārsadda",
    "Qila Abdullāh",
    "Bahāwalnagar",
    "Dādu",
    "Alīābad",
    "Lakki Marwat",
    "Chilās",
    "Pishin",
    "Tānk",
    "Chitrāl",
    "Qila Saifullāh",
    "Shikārpur",
    "Panjgūr",
    "Mastung",
    "Kalāt",
    'Gandāvā',
    "Khānewāl",
    "Nārowāl",
    "Khairpur",
    "Malakand",
    "Vihāri",
    "Saidu Sharif",
    "Jhelum",
    "Mandi Bahāuddīn",
    "Bhakkar",
    "Toba Tek Singh",
    "Jāmshoro",
    "Khārān",
    "Umarkot",
    "Hangu",
    "Timargara",
    'Gākuch',
    "Jacobābād",
    'Alpūrai',
    'Miānwāli',
    "Mūsa Khel Bāzār",
    "Naushahro Fīroz",
    "New Mīrpur",
    "Daggar",
    "Eidgāh",
    'Sibi',
    "Dālbandīn",
    'Rājanpur',
    "Leiah",
    "Upper Dir",
    "Tando Muhammad Khān",
    "Attock",
    "Rāwala Kot",
    "Swābi",
    "Kandhkot",
    "Dasu"
]
export { noUser, noAd, categories, cities }